# Generated by Django 5.2.7 on 2025-11-05 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseCriminal',
            fields=[
                ('case_criminal_id', models.IntegerField(primary_key=True, serialize=False)),
                ('role_in_case', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'case_criminals',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CaseRecord',
            fields=[
                ('case_id', models.IntegerField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('status', models.CharField(max_length=100)),
                ('verdict', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'case_records',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Court',
            fields=[
                ('court_id', models.IntegerField(primary_key=True, serialize=False)),
                ('court_name', models.CharField(max_length=255)),
                ('court_type', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'courts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Criminal',
            fields=[
                ('criminal_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=20)),
                ('address', models.TextField(blank=True, null=True)),
                ('aadhaar_number', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'criminals',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FIR',
            fields=[
                ('fir_id', models.IntegerField(primary_key=True, serialize=False)),
                ('date_registered', models.DateField()),
                ('crime_type', models.CharField(max_length=255)),
                ('incident_location', models.TextField(blank=True, null=True)),
                ('status', models.CharField(max_length=255)),
                ('details', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'firs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PoliceStation',
            fields=[
                ('station_id', models.IntegerField(primary_key=True, serialize=False)),
                ('station_name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('jurisdiction_area', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'police_stations',
                'managed': False,
            },
        ),
    ]
